version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/agent-backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/agent-frontend"
    schedule:
      interval: "weekly"
