/**
 * Constants - Centralized app configuration
 * Dependency Inversion: Values aren't scattered throughout code
 */
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

const VALIDATION = {
  MIN_STRING_LENGTH: 1,
  MAX_STRING_LENGTH: 255,
  MIN_PASSWORD_LENGTH: 8,
};

export default {
  HTTP_STATUS,
  ERROR_CODES,
  PAGINATION,
  VALIDATION,
};
